spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task-manager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: taixinpass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-target: src/main/resources/db/migration/migration_latest_changes.sql
              create-source: metadata

  flyway:
    enable: true
    clean-disabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /apis


#  kafka:
#    bootstrap-servers: localhost:9094

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 2000MB
#      max-request-size: 2000MB
#      file-size-threshold: 2KB
#  data:
#    redis:
#      port: 6379
#      host: localhost

#cloudinary:
#  cloud-name: ${CLOUD-NAME}
#  api-key: ${API-KEY-CLOUDINARY}
#  api-secret: ${API-SECRET-KEY-CLOUDINARY}
#
#jwt:
#  secret-key: ${JWT-SECRET-KEY}